### ISSUE TITLE
Adding a path to root URL

### ISSUE THREAD

**Issue by marknagelberg** [sladkovm/docker-flask-gunicorn-nginx#1]
Thanks for this great repo. 

I'm having no trouble deploying the dash app using a slightly different nginx configuration. I want to run my dash application on http://example.com/path/, rather than just  http://example.com. 

To do this, I changed the project.conf file so ```location /``` becomes ```location /path/```. Here's what it looks like:

```
server {

    listen 80;
    server_name docker_flask_gunicorn_nginx;

    location /path/ {
        proxy_pass http://dash_app:8000;

        # Do not change this
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static {
        rewrite ^/static(.*) /$1 break;
        root /static;
    }
}
```

When I try to run the dash app using this configuration, I get "Error loading layout" in the browser, and looking at the docker logs for the nginx container, I get:

```
2019/02/11 16:26:20 [error] 6#6: *1 open() "/etc/nginx/html/_dash-layout" failed (2: No such file or directory), client: xxx, server: docker_flask_gunicorn_nginx, request: "GET /_dash-layout HTTP/1.1", host: "example.com", referrer: "http://example.com/path/"
 - - [11/Feb/2019:16:26:20 +0000] "GET /_dash-layout HTTP/1.1" 404 571 "http://example.com/path/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "-"
2019/02/11 16:26:20 [error] 6#6: *3 open() "/etc/nginx/html/_dash-dependencies" failed (2: No such file or directory), client: xxx, server: docker_flask_gunicorn_nginx, request: "GET /_dash-dependencies HTTP/1.1", host: "example.com", referrer: "http://example.com/path/"
```

Any idea where I'm going wrong? I'm thinking I'm doing something really simple wrong here but I'm having trouble finding it since I'm not too familiar with nginx.

Thanks!
Mark

**Comment by sladkovm** [comment]
Hi,

I do not remember all the details, but it might be related to the missing rewrite directive, when using a URI subpath:

I would try this:
```
    location /path/ {
        rewrite ^/path/(.*) /$1 break;
        proxy_pass http://dash_app:8000;

        # Do not change this
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

**Comment by marknagelberg** [comment]
Thanks Maksym for your response. Unfortunately your solution didn't work for me, but I was able to figure it out. 

Basically, I had to do two things: add the desired path to the ```url_base_pathname``` argument in the dash app initialization as follows:

```python
app = dash.Dash('dashboard_name',
                server=server,
                url_base_pathname='/path/')
```

And then I updated my ```project.conf``` like this:

```
server {

    listen 80;
    server_name docker_flask_gunicorn_nginx;

    location /path/ {
        proxy_pass http://dash_app:8000/path/;

        # Do not change this
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static {
        rewrite ^/static(.*) /$1 break;
        root /static;
    }
}
```

I'm sure there's probably a better way, but this seems to work!

Thanks again
