### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by ivanpanshin** [sladkovm/docker-flask-gunicorn-nginx#4]
Hey! 

I ran "bash run_docker". Everything seems to be good, up and running (containers are created, so is the network, etc), but when I navigate to the server IP, I get 502 bad gateway error. Based on docker logs for nginx:

2020/04/20 14:59:27 [error] 8#8: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 37.112.0.151, server: docker_flask_gunicorn_nginx, request: "GET / HTTP/1.1", upstream: "http://172.18.0.2:8000/", host: "139.162.133.232"
37.112.0.151 - - [20/Apr/2020:14:59:27 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36" "-"
37.112.0.151 - - [20/Apr/2020:14:59:30 +0000] "GET /favicon.ico HTTP/1.1" 499 0 "http://139.162.133.232/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36" "-"

Could you give me a hand with this?

**Comment by ivanpanshin** [comment]
Found out the issue. Turns out, there is a wrong version of dash in the flask + gunicorn container.

**Comment by vivekpatil94** [comment]
I have same issue, everything was setup properly then got 502 bad gateway.
Please provide details how to resolve this.
